### ISSUE TITLE
Help configuring script

### ISSUE THREAD

**Issue by Nataliya1** [geocortex/geocortex-reporting-client-py#5]
Hello. I learn about this resource today, from the Geocortex Road Ahead webinar, and I would really like to get this to work with my report. 
I downloaded the package from here. Installed the geocortex reporting client. Then I tried to modify the sample.py file and add an item id for my report, but when I run the script I got and error 'ModuleNotFoundError: No module named 'websockets'. Do I have to install 'websockets' module as well? Or maybe I am running/modifying wrong script? Please advice. 

Thank you,
Nataliya

**Comment by ianschmitz** [comment]
Here's a really basic sample I created using an ArcGIS Notebook:

![image](https://user-images.githubusercontent.com/6355370/94865377-50f2f200-03f2-11eb-9363-143890988dda.png)

**Comment by Nataliya1** [comment]
@ianschmitz I got it to work. When I run it the first time I completely removed the 'FeatureIDs=[3903]' from the arguments, since I don't have feature specific arguments in my report, and that's caused the error. I run the script today, and just left the FeatureID list blank 'FeatureIDs=[]', and it worked just fine. Thank you.

**Comment by ianschmitz** [comment]
Glad you got it working!
